import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MobileNavigation } from "../../MobileNavigation";
import { SiteFooter } from "../../SiteFooter";
import { SiteSidebar } from "../../SiteSidebar";
import { getProject, projects } from "../../projects-data";
import { profile } from "../../site-config";
export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const project = getProject((await params).slug); if (!project) return {}; return { title: `${project.name} — ${profile.brand}`, description: project.summary, alternates: { canonical: `/projects/${project.slug}` }, openGraph: { title: `${project.name} — ${profile.brand}`, description: project.summary, url: `/projects/${project.slug}` } }; }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const project = getProject((await params).slug); if (!project) notFound(); return <div className="site-shell project-detail-page"><a className="skip-link" href="#main-content">Skip to content</a><SiteSidebar active="work" /><MobileNavigation active="work" /><main id="main-content" className="page-content"><article className="case-study"><Link className="back-link" href="/projects">← All work</Link><header className="case-study-header"><span className={`status status-${project.status.toLowerCase().replaceAll(" ", "-")}`}>{project.status}</span><h1>{project.name}</h1><p>{project.summary}</p><div className="tag-list">{project.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div></header><section><h2>Problem</h2><p>{project.problem}</p></section><section><h2>Solution</h2><p>{project.solution}</p></section><section><h2>Architecture</h2><p>{project.architecture}</p></section><section><h2>Technical decisions</h2><ul>{project.technicalDecisions.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h2>Challenges</h2><ul>{project.challenges.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h2>Results</h2><p>Public performance metrics are not available for this project.</p></section><section><h2>Current status</h2><p>{project.currentStatus}</p></section></article><SiteFooter /></main></div>; }
