export type Project = {
  slug: "ozon-price-tracker" | "uniassist" | "ru2en-interpreter";
  name: string; summary: string; status: "Published" | "In development" | "Prototype"; capabilities: string[]; technologies: string[];
  problem: string; solution: string; architecture: string; technicalDecisions: string[]; challenges: string[]; currentStatus: string;
  links?: { live?: string; source?: string };
};

export const projects: Project[] = [
  { slug: "ozon-price-tracker", name: "Ozon Price Tracker", summary: "A Chrome extension that turns product-price monitoring into a private, useful history with alerts.", status: "Published", capabilities: ["Product price tracking", "Historical price changes", "Notifications and alerts", "Import and export"], technologies: ["Manifest V3", "React", "TypeScript", "IndexedDB", "Automated tests"], problem: "Shoppers need a simple way to follow product prices over time instead of checking listings manually.", solution: "A Chrome extension that records product prices locally, makes historical changes easy to review, and surfaces alerts when attention is useful.", architecture: "The extension uses a Manifest V3 browser-extension architecture, with a React and TypeScript interface backed by IndexedDB for local price history.", technicalDecisions: ["Use Manifest V3 for the current Chrome extension platform.", "Store price history in IndexedDB so it remains available locally.", "Support import and export so people can keep control of their history.", "Cover important behavior with automated tests."], challenges: ["Keeping price history useful without making routine tracking feel intrusive.", "Designing data portability alongside local-first storage."], currentStatus: "Published." },
  { slug: "uniassist", name: "UniAssist", summary: "A verified-source university information assistant for international students navigating high-stakes decisions.", status: "In development", capabilities: ["Administrator-curated sources", "Retrieval-augmented generation", "Source-grounded answers", "Answer verification"], technologies: ["RAG", "Curated PDFs", "Web content", "Telegram", "MAX"], problem: "International students need dependable university information, but unverified answers can create avoidable risk.", solution: "UniAssist retrieves from administrator-curated PDFs and web content, then grounds and verifies responses before delivering them to students.", architecture: "A retrieval-augmented generation flow connects a curated knowledge base to a response layer and an answer-verification layer, with Telegram and MAX as delivery targets.", technicalDecisions: ["Use administrator-curated material instead of an open web corpus.", "Ground answers in retrieved source material.", "Add an answer-verification layer before delivery.", "Design for Telegram and MAX as distinct delivery targets."], challenges: ["Maintaining a trusted source collection as university information changes.", "Making source-grounded answers clear enough for real student decisions."], currentStatus: "In development." },
  { slug: "ru2en-interpreter", name: "Ru2En Interpreter", summary: "An iOS Russian–English voice interpreter for conversations that need to move naturally in both directions.", status: "Prototype", capabilities: ["Bidirectional translation", "Automatic turn detection", "Speech recognition and text-to-speech", "Conversation history"], technologies: ["iOS", "Speech recognition", "Text-to-speech", "AirPods audio routing"], problem: "Real-time bilingual conversations are difficult when people must repeatedly choose a language, manage turns, and switch between listening and speaking.", solution: "A voice interpreter that supports Russian–English translation in both directions while detecting language and conversational turns automatically.", architecture: "The iOS prototype combines speech recognition, automatic language and turn detection, translation, text-to-speech, conversation history, and AirPods audio routing.", technicalDecisions: ["Treat each conversation as bidirectional rather than a single-direction translation task.", "Use automatic language and turn detection to reduce interaction overhead.", "Support AirPods routing for more natural hands-free use.", "Keep conversation history available for context and review."], challenges: ["Balancing automatic behavior with the ambiguity of live conversation.", "Keeping the audio experience coherent across recognition, translation, and speech output."], currentStatus: "Prototype." },
];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
