export type Project = {
  slug: "openhighlights" | "ozon-price-tracker" | "save-image-as";
  href?: string;
  name: string; summary: string; status: "Published" | "In development" | "Prototype"; capabilities: string[]; technologies: string[];
  problem: string; solution: string; architecture: string; technicalDecisions: string[]; challenges: string[]; currentStatus: string;
  links?: { live?: string; source?: string };
};

export const projects: Project[] = [
  { slug: "save-image-as", href: "/save-image-as", name: "Save Image As PNG", summary: "A private Chrome extension that saves any image as PNG, JPG, WebP or AVIF, converting everything on your own computer.", status: "In development", capabilities: ["Right-click format conversion", "Grab all images and ZIP", "Target file size", "Pick mode for covered images"], technologies: ["Chrome extension", "Manifest V3", "TypeScript", "WebAssembly (AVIF)", "Offscreen document"], problem: "WebP and AVIF images are everywhere, but many editors, upload forms and chat tools still reject them, and existing converters are stale or distrusted.", solution: "Save Image As PNG converts images locally from a right-click, finds lazy-loaded and background images, and keeps the whole process offline and private.", architecture: "A stateless Manifest V3 service worker fetches image bytes, an offscreen document decodes and re-encodes them with canvas and a bundled AVIF encoder, and an on-demand collector finds images without any always-on content scripts.", technicalDecisions: ["No website access at install; per-site access only when an image server requires it.", "Every extension page carries a CSP that forbids network requests.", "Read image dimensions from file headers before decoding to refuse oversized images safely.", "Strip EXIF and GPS metadata by default."], challenges: ["Reading cross-origin images without tainting the canvas.", "Finding the right image under overlays, in shadow DOM and behind lazy loading."], currentStatus: "Built and tested; preparing the Chrome Web Store listing." },
  { slug: "ozon-price-tracker", href: "/ozon-price-tracker", name: "Ozon Price Tracker", summary: "A private Chrome extension that turns Ozon price checks into a useful history with target alerts.", status: "Published", capabilities: ["Automatic price history", "Target-price alerts", "Product dashboard", "Import and export"], technologies: ["Chrome extension", "Manifest V3", "React", "TypeScript", "IndexedDB"], problem: "Ozon prices change often, making it difficult to know whether today’s deal is genuinely good or simply looks urgent.", solution: "Ozon Price Tracker saves product prices over time, makes trends easy to read, and alerts shoppers when a chosen target is reached.", architecture: "A Manifest V3 Chrome extension uses a React and TypeScript interface with IndexedDB for private, local price history.", technicalDecisions: ["Keep price history on the user’s device.", "Use a clear visual timeline instead of isolated price snapshots.", "Support portable backups through import and export.", "Make alerts intentional and product-specific."], challenges: ["Capturing useful price changes without making routine tracking intrusive.", "Presenting enough history for a confident purchase decision without clutter."], currentStatus: "Published as a Chrome extension.", links: { live: "https://chromewebstore.google.com/detail/ozon-price-tracker/dodppojnnlcmbjeenenmpalmiikkmfkh" } },
  { slug: "openhighlights", href: "/openhighlights", name: "OpenHighlights", summary: "A local-first reading library for the passages, notes, and documents you want to keep.", status: "Published", capabilities: ["Web highlights", "Notes and tags", "Local PDF library", "Markdown and JSON export"], technologies: ["Chrome extension", "Local-first storage", "PDF annotations", "Import and export"], problem: "Useful ideas disappear between tabs, bookmarks, and documents, while many reading tools require handing personal research to a cloud service.", solution: "OpenHighlights keeps highlights, notes, saved pages, and PDFs together in a private library stored on the user’s device.", architecture: "A Chrome extension captures and restores highlights on supported pages while keeping the library, attachments, offline snapshots, and PDF files in local browser storage.", technicalDecisions: ["Keep user data local by default.", "Support portable Markdown and JSON exports.", "Make web pages and PDFs part of the same searchable library.", "Preview imported data before adding it."], challenges: ["Restoring durable highlights when web pages change.", "Keeping imported reading history useful when source exports do not contain exact DOM anchors."], currentStatus: "Published on the Chrome Web Store.", links: { live: "https://chrome.google.com/webstore/detail/lblgdcjmhddgpphgbpihphfnnmagnmhk" } },
];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
