export type Project = {
  slug: "openhighlights" | "ozon-price-tracker";
  href?: string;
  name: string; summary: string; status: "Published" | "In development" | "Prototype"; capabilities: string[]; technologies: string[];
  problem: string; solution: string; architecture: string; technicalDecisions: string[]; challenges: string[]; currentStatus: string;
  links?: { live?: string; source?: string };
};

export const projects: Project[] = [
  { slug: "ozon-price-tracker", href: "/ozon-price-tracker", name: "Ozon Price Tracker", summary: "A private Chrome extension that turns Ozon price checks into a useful history with target alerts.", status: "Published", capabilities: ["Automatic price history", "Target-price alerts", "Product dashboard", "Import and export"], technologies: ["Chrome extension", "Manifest V3", "React", "TypeScript", "IndexedDB"], problem: "Ozon prices change often, making it difficult to know whether today’s deal is genuinely good or simply looks urgent.", solution: "Ozon Price Tracker saves product prices over time, makes trends easy to read, and alerts shoppers when a chosen target is reached.", architecture: "A Manifest V3 Chrome extension uses a React and TypeScript interface with IndexedDB for private, local price history.", technicalDecisions: ["Keep price history on the user’s device.", "Use a clear visual timeline instead of isolated price snapshots.", "Support portable backups through import and export.", "Make alerts intentional and product-specific."], challenges: ["Capturing useful price changes without making routine tracking intrusive.", "Presenting enough history for a confident purchase decision without clutter."], currentStatus: "Published as a Chrome extension." },
  { slug: "openhighlights", href: "/openhighlights", name: "OpenHighlights", summary: "A local-first reading library for the passages, notes, and documents you want to keep.", status: "In development", capabilities: ["Web highlights", "Notes and tags", "Local PDF library", "Markdown and JSON export"], technologies: ["Chrome extension", "Local-first storage", "PDF annotations", "Import and export"], problem: "Useful ideas disappear between tabs, bookmarks, and documents, while many reading tools require handing personal research to a cloud service.", solution: "OpenHighlights keeps highlights, notes, saved pages, and PDFs together in a private library stored on the user’s device.", architecture: "A Chrome extension captures and restores highlights on supported pages while keeping the library, attachments, offline snapshots, and PDF files in local browser storage.", technicalDecisions: ["Keep user data local by default.", "Support portable Markdown and JSON exports.", "Make web pages and PDFs part of the same searchable library.", "Preview imported data before adding it."], challenges: ["Restoring durable highlights when web pages change.", "Keeping imported reading history useful when source exports do not contain exact DOM anchors."], currentStatus: "In development for the Chrome Web Store." },
];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
